import { SampleHeirloom } from './types';

export const SAMPLE_HEIRLOOMS: SampleHeirloom[] = [
  {
    id: 'pocket-watch',
    name: '1924 Victorian Brass Pocket Watch',
    subtitle: 'Wound by four generations across Mumbai & London',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80',
    description: 'An engraved mechanical timepiece with Roman numerals, winding crown patina, and subtle glass hairline fractures.',
    estimatedEra: 'Early 20th Century (1924)',
    origin: 'South Asian & British Diaspora Lineage',
    defaultScanResult: {
      object: '1924 Victorian Brass Pocket Watch',
      confidence: 0.98,
      estimatedEra: 'Early 20th Century (1924)',
      detectedMaterial: 'Hand-Engraved Brass, Glass & Swiss Movement Core',
      culturalNote: 'Wound at dusk every Sunday, anchoring family time through migrations.',
      details: [
        'Intricate scrollwork filigree hand-carved along the outer bezel',
        'Warm oxidized golden patina from decades of pocket friction',
        'Subtle crystal scratch near the 7-hour mark recalling a wartime journey',
      ],
      tags: [
        {
          id: 'tag-1',
          label: 'Filigree Bezel',
          detail: 'Master artisan hand-engraved floral arabesques along the case',
          x: 48,
          y: 35,
          category: 'craft',
        },
        {
          id: 'tag-2',
          label: 'Aged Patina',
          detail: 'Oxidized copper-brass sheen worn smooth by ancestral hands',
          x: 65,
          y: 52,
          category: 'wear',
        },
        {
          id: 'tag-3',
          label: 'Winding Crown',
          detail: 'Heavy fluted mechanical crown with tactile heirloom clicking',
          x: 35,
          y: 68,
          category: 'material',
        },
      ],
    },
  },
  {
    id: 'silk-ikat',
    name: 'Handwoven Crimson Silk Ikat Shawl',
    subtitle: 'Dyed with pomegranate rinds and natural madder',
    imageUrl: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=800&q=80',
    description: 'Traditional resist-dyed textile with geometric heritage motifs and pure silk tassel fringe.',
    estimatedEra: 'Mid-20th Century (circa 1952)',
    origin: 'Silk Road & Deccan Weaver Guilds',
    defaultScanResult: {
      object: 'Handwoven Crimson Silk Ikat Shawl',
      confidence: 0.96,
      estimatedEra: 'Mid-20th Century (circa 1952)',
      detectedMaterial: 'Pure Mulberry Silk & Vegetable-Dyed Crimson Weft',
      culturalNote: 'Draped over brides and elders during sacred blessings.',
      details: [
        'Blurred double-ikat diamond pattern requiring master loom counting',
        'Rich madder red hue preserved from organic plant fermentation',
        'Hand-knotted gold zari fringes along the ceremonial border',
      ],
      tags: [
        {
          id: 'tag-1',
          label: 'Double Ikat Weft',
          detail: 'Precision resist-dyeing technique passed through family guilds',
          x: 45,
          y: 38,
          category: 'craft',
        },
        {
          id: 'tag-2',
          label: 'Zari Border',
          detail: 'Pure silver-wound thread dipped in molten gold',
          x: 68,
          y: 62,
          category: 'material',
        },
        {
          id: 'tag-3',
          label: 'Organic Madder Hue',
          detail: 'Sun-dried botanical dye showing soft natural aging',
          x: 32,
          y: 50,
          category: 'wear',
        },
      ],
    },
  },
  {
    id: 'spice-box',
    name: 'Carved Rosewood Masala Dabba',
    subtitle: 'Held the sacred cardamom and turmeric of seven generations',
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    description: 'Hand-carved wooden heirloom container with seven concentric brass bowls and floral lid inlays.',
    estimatedEra: 'Late 19th Century (circa 1895)',
    origin: 'Kerala & Western Ghats Timber Crafts',
    defaultScanResult: {
      object: 'Carved Rosewood Masala Dabba',
      confidence: 0.97,
      estimatedEra: 'Late 19th Century (circa 1895)',
      detectedMaterial: 'Solid Dark Rosewood with Hand-hammered Brass Inserts',
      culturalNote: 'The fragrant beating heart of the ancestral kitchen hearth.',
      details: [
        'Deep patina saturated with decades of clove, cardamom, and sandalwood oils',
        'Chiseled lotus carving on lid symbolizing abundance and renewal',
        'Seven nested hammered brass cups with smooth thumb indentation',
      ],
      tags: [
        {
          id: 'tag-1',
          label: 'Lotus Relief',
          detail: 'Hand-chiseled wood relief honoring the hearth deity',
          x: 50,
          y: 30,
          category: 'craft',
        },
        {
          id: 'tag-2',
          label: 'Aromatic Patina',
          detail: 'Centuries of spice oil absorption giving a dark glowing luster',
          x: 62,
          y: 58,
          category: 'wear',
        },
        {
          id: 'tag-3',
          label: 'Hammered Brass',
          detail: 'Beaten brass cups forged over charcoal anvils',
          x: 36,
          y: 64,
          category: 'material',
        },
      ],
    },
  },
  {
    id: 'pooja-lamp',
    name: 'Hand-Cast Brass Diya Pooja Lamp',
    subtitle: 'Lit every Diwali evening to welcome ancestral grace',
    imageUrl: 'https://images.unsplash.com/photo-1603555501671-8f96b3fce8b4?auto=format&fit=crop&w=800&q=80',
    description: 'Traditional five-wick brass oil lamp topped with a sculpted Mayura peacock crest.',
    estimatedEra: 'Early 20th Century (1910s)',
    origin: 'Tanjore & Swamimalai Bronze Casting Guilds',
    defaultScanResult: {
      object: 'Hand-Cast Brass Diya Pooja Lamp',
      confidence: 0.99,
      estimatedEra: 'Early 20th Century (circa 1915)',
      detectedMaterial: 'Lost-Wax Cast Bell Metal & Forged Golden Brass',
      culturalNote: 'Kindled with sesame oil and cotton wicks at sunrise and twilight.',
      details: [
        'Sculpted Mayura peacock crest crowning the central oil pillar',
        'Five stepped wick troughs seasoned with ceremonial camphor and oil smoke',
        'Deep circular drip base catching holy ghee offerings across festivals',
      ],
      tags: [
        {
          id: 'tag-1',
          label: 'Peacock Finial',
          detail: 'Ancient lost-wax casting technique capturing plumage contours',
          x: 50,
          y: 22,
          category: 'craft',
        },
        {
          id: 'tag-2',
          label: 'Five-Wick Basin',
          detail: 'Beaten brass reservoir shaped to face the cardinal directions',
          x: 48,
          y: 55,
          category: 'material',
        },
        {
          id: 'tag-3',
          label: 'Sacred Smoke Patina',
          detail: 'Soot and sandalwood incense darkening the upper stem',
          x: 65,
          y: 40,
          category: 'wear',
        },
      ],
    },
  },
  {
    id: 'vintage-camera',
    name: '1954 Classic Rangefinder Camera',
    subtitle: 'Captured our family weddings and migrations across continents',
    imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=800&q=80',
    description: 'Heavy mechanical 35mm rangefinder with manual shutter speed dial and vulcanite leatherette grip.',
    estimatedEra: 'Mid-Century Modern (1954)',
    origin: 'German & Post-War Optical Engineering',
    defaultScanResult: {
      object: '1954 Classic Rangefinder Camera',
      confidence: 0.98,
      estimatedEra: 'Mid-Century Modern (1954)',
      detectedMaterial: 'Machined Satin Chrome & Vulcanite Leatherette Body',
      culturalNote: 'Preserved the smiles, travels, and milestone tears of three generations.',
      details: [
        'Knurled brass shutter wheel with crisp mechanical click timings',
        'Twin optical rangefinder windows showing vintage yellow tinting',
        'Worn chrome corner edges where grandfather held it steady for family portraits',
      ],
      tags: [
        {
          id: 'tag-1',
          label: 'Coated Lens',
          detail: 'Multi-coated glass element reflecting amber and cyan hues',
          x: 52,
          y: 48,
          category: 'craft',
        },
        {
          id: 'tag-2',
          label: 'Shutter Dial',
          detail: 'Machined mechanical dial calibrated from 1s to 1/1000s',
          x: 35,
          y: 25,
          category: 'material',
        },
        {
          id: 'tag-3',
          label: 'Corner Wear',
          detail: 'Natural brass exposure revealing decades of travel and weddings',
          x: 75,
          y: 65,
          category: 'wear',
        },
      ],
    },
  },
  {
    id: 'gold-jhumka',
    name: 'Ancestral Gold Filigree Jhumka',
    subtitle: 'Gifted upon marriage and blessed across four generations',
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
    description: 'Intricate 22-karat gold bell earrings with delicate wire filigree and seed pearl drops.',
    estimatedEra: 'Late 19th Century (circa 1880)',
    origin: 'Royal Rajasthani Goldsmith Guilds',
    defaultScanResult: {
      object: 'Ancestral Gold Filigree Jhumka',
      confidence: 0.97,
      estimatedEra: 'Late 19th Century (circa 1880)',
      detectedMaterial: '22K Hand-beaten Gold, Kundan Inlay & Natural Seed Pearls',
      culturalNote: 'Worn close to the cheek on wedding dawns and auspicious ceremonies.',
      details: [
        'Delicate wire filigree forming floral rosettes on the upper stud',
        'Suspended seed pearl tassels that chime gently with every movement',
        'Mellow 22-karat gold luster untarnished across 140 years',
      ],
      tags: [
        {
          id: 'tag-1',
          label: 'Kundan Setting',
          detail: 'Pure gold foil stone-setting technique passed through royal courts',
          x: 50,
          y: 28,
          category: 'craft',
        },
        {
          id: 'tag-2',
          label: 'Pearl Fringe',
          detail: 'Hand-strung freshwater seed pearls on gold wire links',
          x: 50,
          y: 72,
          category: 'material',
        },
        {
          id: 'tag-3',
          label: 'Dome Bell',
          detail: 'Hand-beaten hollow gold dome with geometric perforation',
          x: 65,
          y: 50,
          category: 'wear',
        },
      ],
    },
  },
];
